### ISSUE TITLE
Doesn't work on MacBook Air M1 2020

### ISSUE THREAD

**Issue by Kevinparra535** [NahueTomas/upscayl-node#1]
I'm trying to run the project on my Mac, but Upscaler is trying to find a binary and it doesn't exist

```javascript
const run = async () => {
  await upscaler.init();

  console.log('Upscaler initialized');

  const outputImagePath = await upscaler.upscaleImage(
    join(__dirname, './image-test.png'),
    join(__dirname, './image-test-result.png'),
  );
};

run();
```

Error:
```bash
Upscaler initialized
progress [----------------------------------------] 0% | ETA: 0s | 0/100
Error: spawn /Users/kevinparralopez/Documents/Proyectos/upscayl-node/src/upscaler/sub-classes/driver/command-upscayl/resources/mac/bin/upscayl-bin EACCES
```

**Comment by NahueTomas** [comment]
Hi!
It looks like a permission error, please check if the folder where you are running the project has enough permissions.
Something to keep in mind is that this library needs to run a binary, so probably the error could come from there.

https://www.macinstruct.com/tutorials/how-to-set-file-permissions-on-a-mac/
Here is an example:
```bash
$ cd /projects/test-upscaler
$ chmod -R a+rwx .
$ node index.js
```
PD: Be careful with the folders that you give permissions.

**Comment by Kevinparra535** [comment]
Great, It's working

**Comment by nhannguyen512** [comment]
I am encountering a similar issue on Mac Silicon. Simply running the command chmod +x node_modules/upscayl-node/dist/upscaler/sub-classes/driver/command-upscayl/resources/mac/bin/upscayl-bin resolves it. However, when I build the application using Electron Forge, the same error occurs.

How can I ask customers to run chmod? Can you fix this issue? For example:

"postinstall": "chmod +x ./node_modules/upscayl-node/dist/upscaler/sub-classes/driver/command-upscayl/resources/mac/bin/upscayl-bin"

**Comment by NahueTomas** [comment]
Change applied!
Thanks for the suggestion :)

PR #3
