### ISSUE TITLE
How to add more model ? and have a error con tsconfig.json

### ISSUE THREAD

**Issue by nhannguyen512** [NahueTomas/upscayl-node#2]
No inputs were found in config file 'node_modules/upscayl-node/tsconfig.json'. Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '["node_modules"]'.

**Comment by NahueTomas** [comment]
If you're using [this as a npm package](https://www.npmjs.com/package/upscayl-node) you can use the existing method to add extra models. I recommend to use this ones: https://github.com/upscayl/custom-models

Example:
```javascript
const { join } = require("path");
const { upscaler } = require("upscayl-node");

const run = async () => {
  await upscaler.init();
  const newCustomModel = upscaler.addModel(join(__dirname, "./custom-models/custom-model"));  // Should be the model's name without file extension

  const outputImagePath = await upscaler.upscaleImage(
    join(__dirname, "./image-test.png"),
    join(__dirname, "./image-test-result.png"),
    {
      model: newCustomModel,
    }
  );
};

run().catch(err => console.log(err));
```
